module.exports = {
  MBTI: {
    INFP: "INFP",
    INFJ: "INFJ",
    ENFP: "ENFP",
    ENFJ: "ENFJ",
    INTJ: "INTJ",
    INTP: "INTP",
    ENTP: "ENTP",
    ENTJ: "ENTJ",
    ISFP: "ISFP",
    ISFJ: "ISFP",
    ESFP: "ESFP",
    ESFJ: "ESFJ",
    ISTP: "ISTP",
    ISTJ: "ISTJ",
    ESTP: "ESTP",
    ESTJ: "ESTJ",
  },
  Enneagram: {
    "1w2": "1w2",
    "2w3": "2w3",
    "3w2": "3w2",
    "3w4": "3w4",
    "4w3": "4w3",
    "4w5": "4w5",
    "5w4": "5w4",
    "5w6": "5w6",
    "6w5": "6w5",
    "6w7": "6w7",
    "7w6": "7w6",
    "7w8": "7w8",
    "8w7": "8w7",
    "8w9": "8w9",
    "9w8": "9w8",
    "9w1": "9w1",
  },
  Zodiac: {
    Aries: "Aries",
    Taurus: "Taurus",
    Gemini: "Gemini",
    Cancer: "Cancer",
    Leo: "Leo",
    Virgo: "Virgo",
    Libra: "Libra",
    Scorpio: "Scorpio",
    Sagittarius: "Sagittarius",
    Capricorn: "Capricorn",
    Aquarius: "Aquarius",
    Pisces: "Pisces",
  },
};
